sudo: required
dist: trusty

language: cpp
compiler: gcc

env:
  - CONFIG=debug     VERA=true    SUFFIX=-d
  - CONFIG=release   VERA=false   SUFFIX=

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-5 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - sudo add-apt-repository ppa:smspillaz/verapp-latest -y
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev libboost-wave-dev tcl -y
  - sudo apt-get install vera++ -y
  - sudo apt-get install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev xbitmaps xterm libqt5svg5-dev qttools5-dev qtscript5-dev -y
  - sudo apt-get install xvfb -y
  - Xvfb :0 &
  - export DISPLAY=:0

script:
  - gcc --version
  - qmake --version
  - if [ "$VERA" = "true" ]; then tclsh vera++/generatePaths.tcl; fi
  - if [ "$VERA" = "true" ]; then vera++ --error -p allRules --root vera++ <vera++/params; fi
  - qmake trikRuntime.pro CONFIG+=$CONFIG
  - make -j2
  - cd tests
  - qmake -r CONFIG+=$CONFIG tests.pro
  - make -j2
  - cd minimalCppApp
  - qmake -r CONFIG+=$CONFIG minimalCppApp.pro
  - make -j2
  - cd ../../bin/x86-$CONFIG
  - ls -A
  - sh -c "./trikScriptRunnerTests-x86$SUFFIX"
  - sh -c "./trikCommunicatorTests-x86$SUFFIX"
  - sh -c "./trikKernelTests-x86$SUFFIX"
  - cd ../..
  - if [ "$CONFIG" = "debug" ]; then find . -type f -name '*.gcno' -exec gcov -pb {} +; fi

after_success:
  - if [ "$CONFIG" = "debug" ]; then bash <(curl -s https://codecov.io/bash); fi
