os:
  - linux
  - osx

compiler:
  - gcc

addons:
  apt:
    packages:
      - python-pip

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env:
        - CONFIG=release   VERA=false   SUFFIX=
        - CONFIG=debug     VERA=true    SUFFIX=
    - os: osx
      osx_image: 9.latest
      env:
        - CONFIG=release
git:
  depth: 1

language: cpp


before_install:
  - ./.travis/before_install.sh


install:
  - docker pull trikset/linux-builder

script:
  - ./.travis/script.sh

after_success:
  - if [ "$CONFIG" = "debug" ]; then codecov; fi
