sudo: required

language: cpp

env:
  - CONFIG=debug     VERA=true    SUFFIX=-d
  - CONFIG=release   VERA=false   SUFFIX=

services:
  - docker

install:
  - docker pull yuriilitvinov/trikruntime-builder

script:
  - docker run yuriilitvinov/trikruntime-builder /bin/sh -c "cd ~ && git clone https://github.com/trikset/trikRuntime && cd trikRuntime && qmake CONFIG+=$CONFIG && make -j2"
