clone_folder: c:\trik-runtime

environment:
  global:
    PYTHON_PATH: C:\Python27
    PYTHON_LIB: C:\Python27\libs
    PROJECT_FILE: trikRuntime
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=6 -md=128m
    BUILD_DIR: '%APPVEYOR_BUILD_FOLDER%\.build'

  matrix:
      - MINGW: C:\Qt\Tools\mingw530_32
        QTDIR: C:\Qt\5.11.1\mingw53_32
      - MINGW: C:\Qt\Tools\mingw492_32
        QTDIR: C:\Qt\5.6.3\mingw49_32

configuration:
# - debug
  - release

cache:
  - '%BUILD_DIR%'
before_build:
  - git submodule update --init --recursive
  - set PATH=%QTDIR%\bin;%MINGW%\bin;C:\msys64\usr\bin;%PYTHON_PATH%\bin;%PATH%
  - if not exist %BUILD_DIR% md %BUILD_DIR%
  - du -sh %BUILD_DIR%
  - pacman --verbose --noconfirm --sync ccache rsync
  - curl https://raw.githubusercontent.com/MestreLion/git-tools/master/git-restore-mtime-bare > .fix-mtime.py
  - python .fix-mtime.py
  - git submodule foreach --recursive python %cd%\.fix-mtime.py

build_script:
  - cd %BUILD_DIR%
  - qmake %APPVEYOR_BUILD_FOLDER%\%PROJECT_FILE%.pro -spec win32-g++ CONFIG+=%CONFIGURATION%
  - mingw32-make -j2 qmake_all
  - mingw32-make -j2 all
  - qmake %APPVEYOR_BUILD_FOLDER%\tests\tests.pro -spec win32-g++ CONFIG+=%CONFIGURATION% -o tests.mak
  - mingw32-make -f tests.mak -j2 qmake_all
  - mingw32-make -f tests.mak -j2 all

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd bin\x86-%CONFIGURATION%
  - .\trikScriptRunnerTests
  - .\trikCommunicatorTests
  - .\trikKernelTests

artifacts:
 - path: bin\x86-$(configuration)
   name: trikRuntime-win32-$(configuration)
