clone_folder: c:\trik-runtime

skip_commits:
  files:
    - 'scripts/*'
    - '.travis.yml'
    - 'docker/*'
    - '**/*.html'
    - '**/*.txt'
    - '**/*.md'
    - '.mergify.yml'
    - '.github/mergeable.yml'
  message: /\[NOCI\]/


environment:
  global:
    PROJECT_FILE: trikRuntime
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=3 -md=32m
    BUILD_DIR: '%APPVEYOR_BUILD_FOLDER%\.build'

  matrix:
      - MINGW: C:\Qt\Tools\mingw730_32
        QTDIR: C:\Qt\5.12\mingw73_32
        PYTHON_PATH: C:\Python38
        CONFIGURATION: debug
      - MINGW: C:\Qt\Tools\mingw730_32
        QTDIR: C:\Qt\5.12\mingw73_32
        PYTHON_PATH: C:\Python38
        CONFIGURATION: release
      - MINGW: C:\Qt\Tools\mingw730_64
        QTDIR: C:\Qt\5.12\mingw73_64
        PYTHON_PATH: C:\Python38-x64
        CONFIGURATION: release
      - MINGW: C:\Qt\Tools\mingw730_32
        QTDIR: C:\Qt\5.14\mingw73_32
        PYTHON_PATH: C:\Python38
        CONFIGURATION: release
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

#cache:
#  - '%BUILD_DIR% -> **\*.pr?, appveyor.yml'

init:
  #  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.symlinks true
  - git config --global core.autocrlf true
  - if "x%appveyor_pull_request_number%" NEQ "x" set APPVEYOR_CACHE_SKIP_SAVE=true
  - if "x%appveyor_repo_branch%" NEQ "xmaster" set APPVEYOR_CACHE_SKIP_SAVE=true
before_build:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_PATH%;%QTDIR%\bin;%MINGW%\bin;C:\msys64\usr\bin;%PATH%
  - if not exist %BUILD_DIR% md %BUILD_DIR%
  - du -sh %BUILD_DIR%
  - path
  - python -V
  - g++ --version
# deal with 2020 summer package upgrade problem, when keys changed
  - curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
  - curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
  - pacman --noconfirm -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz || bash -lc 'pacman --noconfirm -U --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz'
# Deal with December 2020 MSYS2 update: update core files to migrate to zstd compression
  - curl -O http://repo.msys2.org/msys/x86_64/zstd-1.4.7-1-x86_64.pkg.tar.xz # the latest in xz
  - curl -O http://repo.msys2.org/msys/x86_64/pacman-5.2.2-5-x86_64.pkg.tar.xz # the latest in xz
  - pacman --verbose --noconfirm --disable-download-timeout -U zstd-1.4.7-1-x86_64.pkg.tar.xz pacman-5.2.2-5-x86_64.pkg.tar.xz # Upgrade now (Dec 2020) needs zstd decompressor
  - cmd /c "pacman --verbose --noconfirm --disable-download-timeout -Syuu" #Full update of core files
  - cmd /c "pacman --verbose --noconfirm --disable-download-timeout -Sy" #Update core files if databases list was changed
  - pacman --verbose --noconfirm --sync rsync make


build_script:
  - cd %BUILD_DIR%
  - qmake %APPVEYOR_BUILD_FOLDER%\%PROJECT_FILE%.pro -spec win32-g++ CONFIG+=%CONFIGURATION% CONFIG+=tests
    #  - ps: $blockRdp = $true;iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  - make -j2 qmake_all
  - make -j2 all

test_script:
  - cd %BUILD_DIR%
  - cd bin\x86-%CONFIGURATION%
  - set TRIK_PYTHONPATH=%PYTHON_PATH%\Lib
  - .\trikKernelTests
  - .\trikCommunicatorTests
  - .\trikCameraPhotoTests
  - .\trikJsRunnerTests
  - .\trikPyRunnerTests
#Uncomment if needed
#artifacts:
# - path: .build\bin\x86-$(configuration)
#   name: trikRuntime-win32-$(configuration)
