clone_folder: c:\trik-runtime

skip_commits:
  files:
    - 'scripts/*'
    - '.travis.yml'
    - 'docker/*'
    - '**/*.html'
    - '**/*.txt'
    - '**/*.md'
  message: /\[NOCI\]/


environment:
  global:
    PYTHON_PATH: C:\Python35
    PYTHON_LIB: '%PYTHON_PATH%\libs'
    PROJECT_FILE: trikRuntime
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=3 -md=32m
    BUILD_DIR: '%APPVEYOR_BUILD_FOLDER%\.build'

  matrix:
      - MINGW: C:\Qt\Tools\mingw730_32
        QTDIR: C:\Qt\5.12\mingw73_32
      - MINGW: C:\Qt\Tools\mingw730_64
        QTDIR: C:\Qt\5.12\mingw73_64

configuration:
  - debug
  - release

cache:
  - '%BUILD_DIR% -> **\*.pr?, appveyor.yml'

init:
  - git config --global core.autocrlf true
  - if "x%appveyor_pull_request_number%" NEQ "x" set APPVEYOR_CACHE_SKIP_SAVE=true
  - if "x%appveyor_repo_branch%" NEQ "xmaster" set APPVEYOR_CACHE_SKIP_SAVE=true

before_build:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_PATH%;%QTDIR%\bin;%MINGW%\bin;C:\msys64\usr\bin;%PATH%
  - if not exist %BUILD_DIR% md %BUILD_DIR%
  - du -sh %BUILD_DIR%
  - pacman --verbose --noconfirm --sync ccache rsync curl
  - path
  - python -V
  - g++ --version
  - curl https://raw.githubusercontent.com/MestreLion/git-tools/master/git-restore-mtime-bare > .fix-mtime.py
  - python "%PYTHON_PATH%\Tools\scripts\2to3.py" -v -p -w -n -f all .fix-mtime.py
  - sed -ri "s#line.(startswith|split)\(#line.\1\(b#g" .fix-mtime.py
  - python .fix-mtime.py
  - git submodule foreach --recursive python %cd%\.fix-mtime.py

build_script:
  - cd %BUILD_DIR%
  - qmake %APPVEYOR_BUILD_FOLDER%\%PROJECT_FILE%.pro -spec win32-g++ CONFIG+=%CONFIGURATION% CONFIG+=tests
  - mingw32-make -j2 qmake_all
  - mingw32-make -j2 all

test_script:
  - cd %BUILD_DIR%
  - cd bin\x86-%CONFIGURATION%
  - if %CONFIGURATION% == debug set CONFIGURATION_SUFFIX=-d
  - .\trikKernelTests%CONFIGURATION_SUFFIX%
  - .\trikCommunicatorTests%CONFIGURATION_SUFFIX%
  - .\trikScriptRunnerTests%CONFIGURATION_SUFFIX%
  - .\trikCameraPhotoTests%CONFIGURATION_SUFFIX%

artifacts:
 - path: .build\bin\x86-$(configuration)
   name: trikRuntime-win32-$(configuration)

notifications:
  - provider: Slack
    incoming_webhook:
      secure: QRFxYnwQHitjlrmGleW/IvNXUciFrbLfMfUWJZJKMd7C4G39APa9IkFMmNO129P7kjgCIRevlyisi7L2DX5WOS0tyvxt6rhiq+g7Dn2rz74=
