clone_folder: c:\trikRuntime
test: off

environment:
  global:
    MINGW: C:\Qt\Tools\mingw492_32
    QTDIR: C:\Qt\5.5\mingw492_32

configuration:
  - debug
  - release

before_build:
  - set PATH=%QTDIR%\bin;%MINGW%\bin;%WINDIR%\system32;%WINDIR%;%WINDIR%\System32\WindowsPowerShell\v1.0\;

build_script:
  - qmake trikRuntime.pro -r -spec win32-g++ CONFIG+=%CONFIGURATION%
  - mingw32-make -j2
