version: 2.1
jobs:
  lint:
    docker:
    - image: trikset/linux-builder
    environment:
    - BASH_ENV: /etc/profile
    shell: /bin/bash -leo pipefail
    steps:
    - run: Xfvb :0 &
    - checkout
    - run: git submodule update --init --recursive --jobs 4 --depth 1 --single-branch
    - run: 'true'
  
workflows:
  main:
    jobs:
    - lint
